"""Type stub for the PyO3 extension module ``pedigree_graph._native`` (ADR 0007)."""

import numpy as np
from numpy.typing import NDArray

def core_version() -> str: ...
def is_topological(mother_rows: NDArray[np.int32], father_rows: NDArray[np.int32], /) -> bool: ...
def structural_depth(mother_rows: NDArray[np.int32], father_rows: NDArray[np.int32], /) -> NDArray[np.int32]: ...
def depth_major_order(depth: NDArray[np.int32], /) -> tuple[NDArray[np.int64], NDArray[np.int64]] | None: ...
def validate_acyclic(
    ids: NDArray[np.int64], mother_rows: NDArray[np.int32], father_rows: NDArray[np.int32], /
) -> None: ...
